include(FindPackageHandleStandardArgs)

set(grpc_ROOT_DIR ${PROJECT_SOURCE_DIR}/3rdparty/grpc)

set(grpc_INCLUDES ${grpc_ROOT_DIR}/include)

set(grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc++.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libprotobuf.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgpr.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_bad_optional_access.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_base.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_civil_time.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_dynamic_annotations.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_spinlock_wait.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_str_format_internal.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_int128.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_strings.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_raw_logging_internal.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_log_severity.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_strings_internal.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_throw_delegate.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_time.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libabsl_time_zone.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libaddress_sorting.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libcares.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc++_alts.a)
#list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc++_error_details.a)
#list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc++_reflection.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc++_unsecure.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc_plugin_support.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpc_unsecure.a)
#list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libgrpcpp_channelz.a)
#list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libprotoc.a)
list(APPEND grpc_LIBS ${grpc_ROOT_DIR}/lib/libupb.a)

find_package_handle_standard_args(grpc DEFAULT_MSG grpc_LIBS grpc_INCLUDES)